name: flutter_volume
description: A Flutter plugin to control system volume and listen for volume changes on different platforms.
version: 1.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.jsr.flutter_volume_controller
        pluginClass: FlutterVolumeControllerPlugin
      # ios:
      #   pluginClass: FlutterVolumeControllerPlugin
      # macos:
      #   pluginClass: FlutterVolumeControllerPlugin
      # windows:
      #   pluginClass: FlutterVolumeControllerPluginCApi
      # linux:
      #   pluginClass: FlutterVolumeControllerPlugin
